<a href="https://colab.research.google.com/github/SanjayBista1010/PyTorch/blob/main/TorchTensor101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

x= torch.rand(3,3)
print(x)

tensor([[0.7255, 0.2751, 0.3811],
        [0.7604, 0.8149, 0.2509],
        [0.2505, 0.7476, 0.1903]])


In [ ]:
torch.cuda.is_available()

True

In [ ]:
x =torch.empty(2,2)
x
#1.2030e-29
0.0000e+00

tensor([[0.0000e+00, 1.2030e-29],
        [0.0000e+00, 0.0000e+00]])

In [ ]:
z =torch.zeros(3,3)
z

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
a =torch.ones(3,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
import numpy as np
a= np.array([[1,1,2,2],[3,3,4,4]])
a

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [ ]:
b= np.array([[1,2],[3,4]], dtype=float)
b.dtype

dtype('float64')

In [ ]:
b = torch.tensor([[1,2],[3,4]])
b

tensor([[1, 2],
        [3, 4]])

In [ ]:
#properties of torch

print(b.size())
print(b.dtype)
print(b.device)

torch.Size([2, 2])
torch.int64
cpu


In [ ]:
b = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
b

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
print(x[:,1])

tensor([1.2030e-29, 0.0000e+00])


In [ ]:
#reshape
z= torch.arange(1,10)
z= z.view(3,3) #reshape
z

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
if torch.cuda.is_available():
  tensor_gpu = b.to('cuda')
  print(tensor_gpu)

tensor([[1., 2.],
        [3., 4.]], device='cuda:0')


In [ ]:
tensor_gpu.device

device(type='cuda', index=0)

In [ ]:
b = torch.tensor([[1,2,3],[4,5,6]], device='cuda') #can write cuda:0 for slot specification
b.device

device(type='cuda', index=0)

In [ ]:
x = torch.tensor([[10,20,30],
                  [40,50,60],
                  [80,90,100]])

print(x[0])
print(x[1,2])
print(x[-1])

tensor([10, 20, 30])
tensor(60)
tensor([ 80,  90, 100])


In [ ]:
print(x[:,0])
print(x[0:2,:])
print(x[:,1:])
print(x[::2,::2])

tensor([10, 40, 80])
tensor([[10, 20, 30],
        [40, 50, 60]])
tensor([[ 20,  30],
        [ 50,  60],
        [ 90, 100]])
tensor([[ 10,  30],
        [ 80, 100]])


In [ ]:
# fancy indexing

rows =torch.tensor([0,2])
cols =torch.tensor([1,2])
print(x[rows,cols])  #(0,1) and (2,2) position selected

tensor([ 20, 100])


In [ ]:
#boolean mask

mask = x >50

print(mask)
print(x[mask])

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([ 60,  80,  90, 100])


In [ ]:
x[0,0] =1

x[:,1] = torch.tensor([111,222,333])

print(x)

tensor([[  1, 111,  30],
        [ 40, 222,  60],
        [ 80, 333, 100]])


In [ ]:
import time

a= np.random.rand(5000,5000)
start = time.time()
np.dot(a,a)
print('Numpy time:', time.time() - start)

a_t = torch.rand(5000,5000, device='cuda')
torch.cuda.synchronize()
start = time.time()
torch.matmul(a_t,a_t)
torch.cuda.synchronize()
print('PyTorch GPU time:', time.time() - start)

Numpy time: 6.513540506362915
PyTorch GPU time: 0.347609281539917
